// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp0F256hdn1WO4TVM4sICiwwEBgYsYSok',
    appId: '1:709108786175:web:7971923007bf13e94c3dca',
    messagingSenderId: '709108786175',
    projectId: 'final-22413',
    authDomain: 'final-22413.firebaseapp.com',
    storageBucket: 'final-22413.appspot.com',
    measurementId: 'G-SJSXLBMJMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCptDK8r2AtMRo4BjNVoFvUs7UeBTR8WcQ',
    appId: '1:709108786175:android:00d91fe711f45c134c3dca',
    messagingSenderId: '709108786175',
    projectId: 'final-22413',
    storageBucket: 'final-22413.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCucci-yJuxh-aCPjN_fTs6FSV52V15UwE',
    appId: '1:709108786175:ios:83899b6b339b10cd4c3dca',
    messagingSenderId: '709108786175',
    projectId: 'final-22413',
    storageBucket: 'final-22413.appspot.com',
    iosBundleId: 'com.example.logistech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCucci-yJuxh-aCPjN_fTs6FSV52V15UwE',
    appId: '1:709108786175:ios:83899b6b339b10cd4c3dca',
    messagingSenderId: '709108786175',
    projectId: 'final-22413',
    storageBucket: 'final-22413.appspot.com',
    iosBundleId: 'com.example.logistech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp0F256hdn1WO4TVM4sICiwwEBgYsYSok',
    appId: '1:709108786175:web:ab774b5e15e6b20f4c3dca',
    messagingSenderId: '709108786175',
    projectId: 'final-22413',
    authDomain: 'final-22413.firebaseapp.com',
    storageBucket: 'final-22413.appspot.com',
    measurementId: 'G-2T289F515M',
  );
}
